@basUrl = http://localhost:3333
@authToken = {{ authenticate.response.body.access_token }}

# @name create_account
POST {{basUrl}}/accounts
Content-Type: application/json

{
    "name": "Victor Trajano",
    "email": "victor8.silva@koper.com.br",
    "password": "123456"
}

###

# @name authenticate
POST {{basUrl}}/sessions
Content-Type: application/json

{
    "email": "victor8.silva@koper.com.br",
    "password": "123456"
}

###

# @name create_question
POST {{basUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
 "title": "Teste de mais uma 11",
 "content": "Victor é full stack papai 2"   
}

###

# @name list_questions
GET {{basUrl}}/questions?limit=10&offset=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###