@basUrl = http://localhost:3333

# @name create_account
POST {{basUrl}}/accounts
Content-Type: application/json

{
    "name": "Victor Trajano",
    "email": "victor.silva@koper.com.br",
    "password": "123456"
}

###

# @name authenticate
POST {{basUrl}}/sessions
Content-Type: application/json

{
    "name": "Victor Trajano",
    "email": "victor.silva@koper.com.br",
    "password": "123456"
}

###

